### ISSUE TITLE
Location <p> not working

### ISSUE THREAD

**Issue by Foxandxss** [auth0/angular2-the-new-horizon-sample#2]
Bleeding edge reviewer reporting for duty, sir.

The:

``` javascript
<p [innerHTML]="'Location ' + person.location.toString()"></p>
```

That is not working. I tried with [text] which was recommended in a talk but not working either.

I guess you want to show a different way than using {{foo}} but I don't get it working.

Will open a PR if I manage to fix it.

**Comment by areologist** [comment]
I noticed this as well. Tried a few others just out of curiosity, such as [style.color] which worked, but [innerText], [innerHTML], [name], [className], and others... Nope.

**Comment by mgonto** [comment]
I changed from `span` to `p` last minute. That might be it. But weird that `innerText` didn't work either. I'll debug it and see what's going on. That should be working.

**Comment by mgonto** [comment]
Hmmm no idea what's going on.
