### ISSUE TITLE
Bad banner

### ISSUE THREAD

**Issue by Foxandxss** [auth0/angular2-the-new-horizon-sample#3]
I am too perfectionist, but the banner on the webpack config is not correct.

**Comment by Foxandxss** [comment]
Oh, you updated the auth one, that explains the copy & paste :P

**Comment by Foxandxss** [comment]
Package.json has the same issues.

**Comment by mgonto** [comment]
I'll update Thanks

**Comment by mgonto** [comment]
And yes, I updated the Auth one to Typescript :)
