### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by jessejohnson** [auth0/angular2-the-new-horizon-sample#4]
I get these errors when I run `npm install`

`npm WARN package.json rx@2.5.3 No README data
npm WARN package.json angular2@2.0.0-alpha.26 No repository field.
npm WARN package.json rtts_assert@2.0.0-alpha.26 No repository field.
npm WARN unmet dependency /home/odette/Dropbox/Apps/ng2/angular2-the-new-horizon-sample/node_modules/angular2 requires rx@'2.5.1' but will load
npm WARN unmet dependency /home/odette/Dropbox/Apps/ng2/angular2-the-new-horizon-sample/node_modules/rx,
npm WARN unmet dependency which is version 2.5.3
npm WARN unmet dependency /home/odette/Dropbox/Apps/ng2/angular2-the-new-horizon-sample/node_modules/angular2 requires zone.js@'0.5.0' but will load
npm WARN unmet dependency /home/odette/Dropbox/Apps/ng2/angular2-the-new-horizon-sample/node_modules/zone.js,
npm WARN unmet dependency which is version 0.5.1`

I'm new to this. What am I doing wrong?

**Comment by mgonto** [comment]
They're all just warnings I think. I see no error. Right?

**Comment by jessejohnson** [comment]
Ah yes...but then the packages don't get installed.

**Comment by mgonto** [comment]
Hmmm, for me it's working OK. Nothing gets installed on node_modules?

**Comment by jessejohnson** [comment]
There's a bunch of folders in node_modules.
I deleted the folder and run `npm install` again. 
Works fine now.

Thanks :)
